[[redirects]]
from = "/concepts/*"
to = "/intro/:splat"
status = 301

[[redirects]]
from = "/tee-litepaper.pdf"
to = "/intro/resources/"
status = 301
force = true

[[redirects]]
from = "/t1-litepaper.pdf"
to = "/intro/resources/"
status = 301
force = true
