/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  integrationSidebar: [
    {
      type: 'category',
      label: 'xChainRead',
      items: ['integration/xChainRead/overview', 'integration/xChainRead/api-reference'],
    },
    {
      type: 'category',
      label: '7683',
      items: ['integration/7683/solver-integration', 'integration/7683/aggregator-integration'],
    },
  ],
}

module.exports = sidebars
